---

- name: Install sql packages
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - mariadb-server
    - python-pymysql
    - python-mysqldb
- name: Create openstack db conf
  template:
    src: 99-openstack.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf

- name: Start mysql service
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: Set the root password for all root accounts
  mysql_user:
    name: root
    host: '{{ item }}'
    password: '{{ ansible_ssh_pass }}'
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: ansible_host != 'localhost'

- name: Configure mysql for easy access as root user
  template:
    src: my.cnf.j2
    dest: ~/my.cnf
    owner: root
    group: root
    mode: 0644

- name: Ensure anoymous users are not in the database
  mysql_user:
    name: ''
    host: '*'
    state: absent

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Restart mariadb service
  service:
    name: mysql
    state: restarted
    enabled: yes
