---

- name: Install nova-compute package
  apt:
    name: nova-compute
    state: latest

- name: Config nova.conf
  ini_file:
    path: /etc/nova/nova.conf
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: DEFAULT, option: transport_url, value: 'rabbit://openstack:{{ ansible_ssh_pass }}@controller' }
    - { section: api, option: auth_strategy, value: keystone }
    - { section: keystone_authtoken, option: auth_url, value: 'http://controller:5000/v3' }
    - { section: keystone_authtoken, option: memcached_servers, value: 'controller:11211' }
    - { section: keystone_authtoken, option: auth_type, value: password }
    - { section: keystone_authtoken, option: project_domain_name, value: Default }
    - { section: keystone_authtoken, option: user_domain_name, value: Default }
    - { section: keystone_authtoken, option: project_name, value: service }
    - { section: keystone_authtoken, option: username, value: nova }
    - { section: keystone_authtoken, option: password, value: '{{ ansible_ssh_pass }}' }
    - { section: DEFAULT, option: my_ip, value: '{{ ansible_host }}' }
    - { section: DEFAULT, option: use_neutron, value: True }
    - { section: DEFAULT, option: firewall_driver, value: 'nova.virt.firewall.NoopFirewallDriver' }
    - { section: vnc, option: enabled, value: true }
    - { section: vnc, option: server_listen, value: '0.0.0.0' }
    - { section: vnc, option: server_proxyclient_address, value: '$my_ip' }
    - { section: vnc, option: novncproxy_base_url , value: 'http://{{ controller.ansible_host }}:6080/vnc_auto.html' }
    - { section: glance, option: api_servers, value: 'http://controller:9292' }
    - { section: oslo_concurrency, option: lock_path, value: '/var/lib/nova/tmp' }
    - { section: placement, option: region_name, value: RegionOne }
    - { section: placement, option: project_domain_name, value: Default }
    - { section: placement, option: user_domain_name, value: Default }
    - { section: placement, option: project_name, value: service }
    - { section: placement, option: username, value: placement }
    - { section: placement, option: password, value: '{{ ansible_ssh_pass }}' }
    - { section: placement, option: auth_type, value: password }
    - { section: placement, option: auth_url, value: 'http://controller:5000/v3' }

- name: Remove configurations
  ini_file:
    path: /etc/nova/nova.conf
    state: absent
    section: '{{ item.section }}'
    option: '{{ item.option }}'
  with_items:
    - { section: DEFAULT, option: log_dir }

- name: Restart nova-compute service
  service:
    name: nova-compute
    state: restarted
    enabled: yes
