---

- name: Install rabbitmq-server
  apt:
    name: rabbitmq-server
    state: latest
    update_cache: yes

- name: Start rabbitmq-server service
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Add the openstack user
  rabbitmq_user:
    user: openstack
    password: '{{ ansible_ssh_pass }}'
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
