---

- name: Install etcd
  apt:
    name: etcd
    state: latest
    update_cache: yes

- name: Generate etct config
  template:
    src: etcd.j2
    dest: /etc/default/etcd

- name: Start etcd service
  service:
    name: etcd
    state: restarted
    enabled: yes
