---

- name: Install packages
  apt:
    name: neutron-openvswitch-agent
    state: latest

- name: Config neutron.conf
  ini_file:
    path: /etc/neutron/neutron.conf
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: DEFAULT, option: transport_url, value: 'rabbit://openstack:{{ ansible_ssh_pass }}@controller' }
    - { section: DEFAULT, option: auth_strategy, value: keystone }
    - { section: keystone_authtoken, option: www_authenticate_uri, value: 'http://controller:5000' }
    - { section: keystone_authtoken, option: auth_url, value: 'http://controller:5000' }
    - { section: keystone_authtoken, option: memcached_servers, value: 'controller:11211' }
    - { section: keystone_authtoken, option: auth_type, value: password }
    - { section: keystone_authtoken, option: project_domain_name, value: Default }
    - { section: keystone_authtoken, option: user_domain_name, value: Default }
    - { section: keystone_authtoken, option: project_name, value: service }
    - { section: keystone_authtoken, option: username, value: neutron }
    - { section: keystone_authtoken, option: password, value: '{{ ansible_ssh_pass }}' }

- name: Remove configurations
  ini_file:
    path: /etc/neutron/neutron.conf
    state: absent
    section: '{{ item.section }}'
    option: '{{ item.option }}'
  with_items:
    - { section: database, option: connection }

- name: Config openvswitch_agent.ini
  ini_file:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: ovs, option: bridge_mappings, value: 'provider:br-provider' }
    - { section: ovs, option: local_ip, value: '{{ ansible_host }}' }
    - { section: agent, option: tunnel_types, value: vxlan }
    - { section: agent, option: l2_population , value: true }
    - { section: securitygroup, option: enable_security_group , value: true }
    - { section: securitygroup, option: firewall_driver = , value: 'iptables_hybrid' }

- name: Add br_netfilter kernel module
  command: modprobe br_netfilter

- name: Ensure your Linux operating system kernel supports network bridge filters
  blockinfile:
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    path: /etc/sysctl.conf

- name: Execute sysctl
  command: sysctl -p
- name: create ovs provider bridge
  command: ovs-vsctl add-br br-provider
- name: create ovs provider bridge port
  command: ovs-vsctl add-port br-provider enp7s01
  
- name: Config nova.conf
  ini_file:
    path: /etc/nova/nova.conf
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: neutron, option: url, value: 'http://controller:9696' }
    - { section: neutron, option: region_name, value: RegionOne }
    - { section: neutron, option: project_domain_name, value: Default }
    - { section: neutron, option: user_domain_name, value: Default }
    - { section: neutron, option: project_name, value: service }
    - { section: neutron, option: username, value: neutron }
    - { section: neutron, option: password, value: '{{ ansible_ssh_pass }}' }
    - { section: neutron, option: auth_type, value: password }
    - { section: neutron, option: auth_url, value: 'http://controller:5000' }

- name: Restart nova/neutron services
  service:
    name: '{{ item }}'
    state: restarted
    enabled: yes
  with_items:
    - nova-compute
    - neutron-openvswitch-agent
